//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSShutterBugPlugin\src\main\java\com\applidium\shutterbug\cache\LruCache.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "LruCache.h"
#include "java/lang/Boolean.h"
#include "java/lang/Character.h"
#include "java/lang/Float.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/Integer.h"
#include "java/lang/NullPointerException.h"
#include "java/util/Iterator.h"
#include "java/util/LinkedHashMap.h"
#include "java/util/Map.h"
#include "java/util/Set.h"




#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


@interface APLruCache () {
 @public
  JavaUtilLinkedHashMap *map_;
  /*!
   @brief Size of this cache in units.Not necessarily the number of elements.
   */
  int32_t size_;
  int32_t maxSize_;
  int32_t putCount_;
  int32_t createCount_;
  int32_t evictionCount_;
  int32_t hitCount_;
  int32_t missCount_;
}

/*!
 @param maxSize the maximum size of the cache before returning. May be -1 to
              evict even 0-sized elements.
 */
- (void)trimToSizeWithInt:(int32_t)maxSize;

- (int32_t)safeSizeOfWithId:(id)key
                     withId:(id)value;

@end

J2OBJC_FIELD_SETTER(APLruCache, map_, JavaUtilLinkedHashMap *)

__attribute__((unused)) static void APLruCache_trimToSizeWithInt_(APLruCache *self, int32_t maxSize);

__attribute__((unused)) static int32_t APLruCache_safeSizeOfWithId_withId_(APLruCache *self, id key, id value);

@implementation APLruCache

- (instancetype)initWithInt:(int32_t)maxSize {
  APLruCache_initWithInt_(self, maxSize);
  return self;
}

- (id)getWithId:(id)key {
  if (key == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"key == null");
  }
  id mapValue;
  @synchronized(self) {
    mapValue = [((JavaUtilLinkedHashMap *) nil_chk(map_)) getWithId:key];
    if (mapValue != nil) {
      hitCount_++;
      return mapValue;
    }
    missCount_++;
  }
  id createdValue = [self createWithId:key];
  if (createdValue == nil) {
    return nil;
  }
  @synchronized(self) {
    createCount_++;
    mapValue = [map_ putWithId:key withId:createdValue];
    if (mapValue != nil) {
      (void) [map_ putWithId:key withId:mapValue];
    }
    else {
      size_ += APLruCache_safeSizeOfWithId_withId_(self, key, createdValue);
    }
  }
  if (mapValue != nil) {
    [self entryRemovedWithBoolean:false withId:key withId:createdValue withId:mapValue];
    return mapValue;
  }
  else {
    APLruCache_trimToSizeWithInt_(self, maxSize_);
    return createdValue;
  }
}

- (id)putWithId:(id)key
         withId:(id)value {
  if (key == nil || value == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"key == null || value == null");
  }
  id previous;
  @synchronized(self) {
    putCount_++;
    size_ += APLruCache_safeSizeOfWithId_withId_(self, key, value);
    previous = [((JavaUtilLinkedHashMap *) nil_chk(map_)) putWithId:key withId:value];
    if (previous != nil) {
      size_ -= APLruCache_safeSizeOfWithId_withId_(self, key, previous);
    }
  }
  if (previous != nil) {
    [self entryRemovedWithBoolean:false withId:key withId:previous withId:value];
  }
  APLruCache_trimToSizeWithInt_(self, maxSize_);
  return previous;
}

- (void)trimToSizeWithInt:(int32_t)maxSize {
  APLruCache_trimToSizeWithInt_(self, maxSize);
}

- (id)removeWithId:(id)key {
  if (key == nil) {
    @throw new_JavaLangNullPointerException_initWithNSString_(@"key == null");
  }
  id previous;
  @synchronized(self) {
    previous = [((JavaUtilLinkedHashMap *) nil_chk(map_)) removeWithId:key];
    if (previous != nil) {
      size_ -= APLruCache_safeSizeOfWithId_withId_(self, key, previous);
    }
  }
  if (previous != nil) {
    [self entryRemovedWithBoolean:false withId:key withId:previous withId:nil];
  }
  return previous;
}

- (void)entryRemovedWithBoolean:(bool)evicted
                         withId:(id)key
                         withId:(id)oldValue
                         withId:(id)newValue {
}

- (id)createWithId:(id)key {
  return nil;
}

- (int32_t)safeSizeOfWithId:(id)key
                     withId:(id)value {
  return APLruCache_safeSizeOfWithId_withId_(self, key, value);
}

- (int32_t)sizeOfWithId:(id)key
                 withId:(id)value {
  return 1;
}

- (void)evictAll {
  APLruCache_trimToSizeWithInt_(self, -1);
}

- (int32_t)size {
  @synchronized(self) {
    return size_;
  }
}

- (int32_t)maxSize {
  @synchronized(self) {
    return maxSize_;
  }
}

- (int32_t)hitCount {
  @synchronized(self) {
    return hitCount_;
  }
}

- (int32_t)missCount {
  @synchronized(self) {
    return missCount_;
  }
}

- (int32_t)createCount {
  @synchronized(self) {
    return createCount_;
  }
}

- (int32_t)putCount {
  @synchronized(self) {
    return putCount_;
  }
}

- (int32_t)evictionCount {
  @synchronized(self) {
    return evictionCount_;
  }
}

- (id<JavaUtilMap>)snapshot {
  @synchronized(self) {
    return new_JavaUtilLinkedHashMap_initWithJavaUtilMap_(map_);
  }
}

- (NSString *)description {
  @synchronized(self) {
    int32_t accesses = hitCount_ + missCount_;
    int32_t hitPercent = accesses != 0 ? (JreIntDiv(100 * hitCount_, accesses)) : 0;
    return NSString_java_formatWithNSString_withNSObjectArray_(@"LruCache[maxSize=%d,hits=%d,misses=%d,hitRate=%d%%]", [IOSObjectArray newArrayWithObjects:(id[]){ JavaLangInteger_valueOfWithInt_(maxSize_), JavaLangInteger_valueOfWithInt_(hitCount_), JavaLangInteger_valueOfWithInt_(missCount_), JavaLangInteger_valueOfWithInt_(hitPercent) } count:4 type:NSObject_class_()]);
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x11, 1, 2, -1, 3, -1, -1 },
    { NULL, "LNSObject;", 0x11, 4, 5, -1, 6, -1, -1 },
    { NULL, "V", 0x2, 7, 0, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x11, 8, 2, -1, 3, -1, -1 },
    { NULL, "V", 0x4, 9, 10, -1, 11, -1, -1 },
    { NULL, "LNSObject;", 0x4, 12, 2, -1, 3, -1, -1 },
    { NULL, "I", 0x2, 13, 5, -1, 14, -1, -1 },
    { NULL, "I", 0x4, 15, 5, -1, 14, -1, -1 },
    { NULL, "V", 0x11, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x31, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x31, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x31, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x31, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x31, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x31, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x31, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x31, -1, -1, -1, 16, -1, -1 },
    { NULL, "LNSString;", 0x31, 17, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithInt:);
  methods[1].selector = @selector(getWithId:);
  methods[2].selector = @selector(putWithId:withId:);
  methods[3].selector = @selector(trimToSizeWithInt:);
  methods[4].selector = @selector(removeWithId:);
  methods[5].selector = @selector(entryRemovedWithBoolean:withId:withId:withId:);
  methods[6].selector = @selector(createWithId:);
  methods[7].selector = @selector(safeSizeOfWithId:withId:);
  methods[8].selector = @selector(sizeOfWithId:withId:);
  methods[9].selector = @selector(evictAll);
  methods[10].selector = @selector(size);
  methods[11].selector = @selector(maxSize);
  methods[12].selector = @selector(hitCount);
  methods[13].selector = @selector(missCount);
  methods[14].selector = @selector(createCount);
  methods[15].selector = @selector(putCount);
  methods[16].selector = @selector(evictionCount);
  methods[17].selector = @selector(snapshot);
  methods[18].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "map_", "LJavaUtilLinkedHashMap;", .constantValue.asLong = 0, 0x12, -1, -1, 18, -1 },
    { "size_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "maxSize_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "putCount_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "createCount_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "evictionCount_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "hitCount_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "missCount_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "I", "get", "LNSObject;", "(TK;)TV;", "put", "LNSObject;LNSObject;", "(TK;TV;)TV;", "trimToSize", "remove", "entryRemoved", "ZLNSObject;LNSObject;LNSObject;", "(ZTK;TV;TV;)V", "create", "safeSizeOf", "(TK;TV;)I", "sizeOf", "()Ljava/util/Map<TK;TV;>;", "toString", "Ljava/util/LinkedHashMap<TK;TV;>;", "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _APLruCache = { "LruCache", "com.applidium.shutterbug.cache", ptrTable, methods, fields, 7, 0x1, 19, 8, -1, -1, -1, 19, -1 };
  return &_APLruCache;
}

@end

void APLruCache_initWithInt_(APLruCache *self, int32_t maxSize) {
  NSObject_init(self);
  if (maxSize <= 0) {
    @throw new_JavaLangIllegalArgumentException_initWithNSString_(@"maxSize <= 0");
  }
  self->maxSize_ = maxSize;
  self->map_ = new_JavaUtilLinkedHashMap_initWithInt_withFloat_withBoolean_(0, 0.75f, true);
}

APLruCache *new_APLruCache_initWithInt_(int32_t maxSize) {
  J2OBJC_NEW_IMPL(APLruCache, initWithInt_, maxSize)
}

APLruCache *create_APLruCache_initWithInt_(int32_t maxSize) {
  J2OBJC_CREATE_IMPL(APLruCache, initWithInt_, maxSize)
}

void APLruCache_trimToSizeWithInt_(APLruCache *self, int32_t maxSize) {
  while (true) {
    id key;
    id value;
    @synchronized(self) {
      if (self->size_ < 0 || ([((JavaUtilLinkedHashMap *) nil_chk(self->map_)) isEmpty] && self->size_ != 0)) {
        @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$$", [[self java_getClass] getName], @".sizeOf() is reporting inconsistent results!"));
      }
      if (self->size_ <= maxSize || [((JavaUtilLinkedHashMap *) nil_chk(self->map_)) isEmpty]) {
        break;
      }
      id<JavaUtilMap_Entry> toEvict = [((id<JavaUtilIterator>) nil_chk([((id<JavaUtilSet>) nil_chk([((JavaUtilLinkedHashMap *) nil_chk(self->map_)) entrySet])) iterator])) next];
      key = [((id<JavaUtilMap_Entry>) nil_chk(toEvict)) getKey];
      value = [toEvict getValue];
      (void) [self->map_ removeWithId:key];
      self->size_ -= APLruCache_safeSizeOfWithId_withId_(self, key, value);
      self->evictionCount_++;
    }
    [self entryRemovedWithBoolean:true withId:key withId:value withId:nil];
  }
}

int32_t APLruCache_safeSizeOfWithId_withId_(APLruCache *self, id key, id value) {
  int32_t result = [self sizeOfWithId:key withId:value];
  if (result < 0) {
    @throw new_JavaLangIllegalStateException_initWithNSString_(JreStrcat("$@C@", @"Negative size: ", key, '=', value));
  }
  return result;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(APLruCache)

J2OBJC_NAME_MAPPING(APLruCache, "com.applidium.shutterbug.cache", "AP")
